
export const POST_REGISTER_SUCESS = "POST_REGISTER_SUCESS";
export const POST_ADMINREGISTER_SUCESS = "POST_ADMINREGISTER_SUCESS";

export const POST_REGISTER_FAIL = "POST_REGISTER_FAIL";
export const POST_REGISTER_REQUEST = "POST_REGISTER_REQUEST";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCESS = "LOGIN_SUCESS";
export const ADMINLOGIN_SUCESS = "ADMINLOGIN_SUCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";



export const LOGOUT_SUCESS = "LOGOUT_SUCESS";
export const AUTHLOGIN_SUCESS = "AUTHLOGIN_SUCESS";



