
export const POST_REGISTER_DATA = "POST_REGISTER_DATA";
export const POST_REGISTER_DATA = "POST_REGISTER_DATA";
export const POST_REGISTER_DATA = "POST_REGISTER_DATA";

export const GET_REGISTER_DATA = "GET_REGISTER_DATA";
export const GET_REGISTER_DATA = "GET_REGISTER_DATA";
export const GET_REGISTER_DATA = "GET_REGISTER_DATA";
